#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 10 11:48:16 2022

@author: doensen
"""

import xarray as xr
import numpy as np
from matplotlib import pyplot as plt 
path = ''
#%%
